export type Row = readonly [string, string, string, string];
export const options: Row[] = [
  [
    "transport",
    "UploadTransport",
    "Required",
    "Provides create, probe, upload, complete and optional terminate operations. Choose HTTP, chunked or implement your own transport.",
  ],
  [
    "autoUpload",
    "boolean",
    "false",
    'Start accepted files as soon as selection and validation finish. Otherwise call start or use an Action with action="start".',
  ],
  [
    "chunkSize",
    "number, bytes",
    "5242880",
    "Requested chunk size. The server returns the accepted size when creating the session. HTTP sends the entire file in one request.",
  ],
  [
    "maxConcurrentFiles",
    "positive integer",
    "2",
    "How many files can run together. Paused transfers release their slot after their requests stop.",
  ],
  [
    "maxConcurrentChunks",
    "positive integer",
    "1",
    "Independent chunks active per file. Values above one require transport.capabilities.parallelParts.",
  ],
  [
    "maxConcurrentRequests",
    "positive integer",
    "4",
    "Shared limit for data requests, creation, probes, finalization and cleanup.",
  ],
  [
    "retry.maxAttempts",
    "positive integer",
    "4",
    "Includes the first attempt. Four means one initial request and at most three retries per eligible operation.",
  ],
  [
    "retry.baseDelay",
    "non-negative integer, ms",
    "1000",
    "Starting delay for exponential retry backoff.",
  ],
  [
    "retry.maxDelay",
    "non-negative integer, ms",
    "30000",
    "Caps the locally calculated delay. A server Retry-After can request a longer wait.",
  ],
  [
    "retry.jitter",
    "boolean",
    "true",
    "Vary each local retry delay between half and all of the calculated backoff.",
  ],
  [
    "retry.shouldRetry",
    "(error: unknown) => boolean",
    "Built-in policy",
    "Override eligibility. The default retries network failures, timeouts, 408, 429, 500, 502, 503 and 504. User cancellation never retries.",
  ],
  [
    "requestTimeout",
    "non-negative integer, ms",
    "Unset",
    "Abort an individual request after this duration. Zero disables the timer. Resumable operations reconcile uncertain results before retrying.",
  ],
  [
    "progressInterval",
    "non-negative integer, ms",
    "100",
    "Minimum interval between visual progress notifications. Durable confirmations and final states are delivered immediately.",
  ],
  [
    "persistence",
    "UploadPersistence | false",
    "false",
    "Store session metadata and cleanup records. indexedDBPersistence(namespace) supplies the browser implementation. Slow writes keep only the latest waiting checkpoint. File content and auth headers are not saved.",
  ],
  [
    "initialFiles",
    "ExistingUpload[]",
    "[]",
    "Completed server records containing id, metadata and optional result. They render during SSR without a local File.",
  ],
  [
    "loadHistory",
    "(cursor, signal) => Promise<HistoryPage>",
    "Unset",
    "Fetch a page of completed records. Return { items, nextCursor? }. Call store.loadHistory(cursor) to add them to this uploader.",
  ],
  [
    "accept",
    "string",
    "Unset",
    'Comma-separated MIME types, wildcards or extensions, such as "image/*,.pdf". Also set the native Input accept attribute for the system file dialog.',
  ],
  [
    "maxFileSize",
    "non-negative integer, bytes",
    "Unset",
    "Reject a selected file above this size before opening a transfer session.",
  ],
  [
    "maxTotalSize",
    "non-negative integer, bytes",
    "Unset",
    "Maximum combined size of accepted items in this uploader, including completed records.",
  ],
  [
    "maxFiles",
    "non-negative integer",
    "Unset",
    "Maximum number of accepted items. Validation failures do not consume an accepted-file slot.",
  ],
  [
    "validateFile",
    "(file, signal) => Promise<string | void>",
    "Unset",
    "Return an error message to reject selection. Returning nothing accepts the file. Honor the signal during async validation.",
  ],
  [
    "disabled",
    "boolean",
    "false",
    "Block selection and mutation controls. Running transfers continue. Update it through store.setOptions.",
  ],
  [
    "readOnly",
    "boolean",
    "false",
    "Keep the list and output visible while blocking all mutation controls. Running transfers continue.",
  ],
  [
    "onCancel",
    "(session, context) => Promise<void>",
    "transport.terminate",
    "Override temporary-session cleanup. A failed cleanup remains in snapshot.cleanups and can be retried.",
  ],
  [
    "onRemove",
    "(item, signal) => Promise<void>",
    "Unset",
    "Delete a completed file through your application. The row disappears only when this callback succeeds.",
  ],
  [
    "onCompleted",
    "(item) => void | Promise<void>",
    "Unset",
    "Read the server result after finalization has been confirmed.",
  ],
  [
    "onError",
    "(error, item?) => void | Promise<void>",
    "Unset",
    "Receive validation and transfer errors. The item and its error remain available for rendering.",
  ],
];
export const fields: Row[] = [
  [
    "id",
    "string",
    "Generated or existing record ID",
    "Local row identity. Use session.id when referring to a server transfer.",
  ],
  [
    "requestKey",
    "string",
    "Stable per transfer",
    "Idempotency key used for creation. Preserved through retry and refresh. Reset creates a new key.",
  ],
  [
    "file",
    "File | undefined",
    "Selected File",
    "Absent for restored sessions and existing server records. attach associates a reselected file.",
  ],
  [
    "metadata",
    "FileMetadata",
    "File metadata",
    "name, size in bytes, MIME type, lastModified timestamp and optional application metadata.",
  ],
  [
    "status",
    "UploadStatus",
    "idle",
    "Selection, transfer and finalization state. See the state table below.",
  ],
  [
    "session",
    "UploadSession | undefined",
    "Unset",
    "Server id, accepted chunkSize and optional expiresAt timestamp.",
  ],
  [
    "parts",
    "readonly PartReceipt[]",
    "[]",
    "Server-confirmed chunk index, size and lowercase SHA-256. These are checked before reuse after reselecting a file.",
  ],
  [
    "result",
    "unknown",
    "Unset",
    "Your server response from complete. Common results include an ID, URL or application document record.",
  ],
  ["uploadedBytes", "number", "0", "Bytes confirmed as saved by the server."],
  [
    "transferredBytes",
    "number",
    "0",
    "Unique bytes represented by confirmed chunks and current request progress. Retransmitted bytes are not added twice.",
  ],
  ["totalBytes", "number", "File size", "Expected file size in bytes."],
  [
    "remainingBytes",
    "number",
    "File size",
    "Bytes not yet confirmed as saved.",
  ],
  [
    "progress",
    "number | null",
    "0 or null",
    "Percentage from 0 to 100. Null means the transport cannot measure it. Reaching 100 does not imply completed.",
  ],
  [
    "bytesPerSecond",
    "number | null",
    "null",
    "Estimate from recent transfer measurements. Null when paused or when there is not enough data.",
  ],
  [
    "etaSeconds",
    "number | null",
    "null",
    "Estimated remaining transfer time. It does not include work your server performs after the bytes arrive.",
  ],
  [
    "activeMilliseconds",
    "number",
    "0",
    "Time spent in active runs, excluding time paused.",
  ],
  [
    "attempt",
    "number",
    "0",
    "Current operation attempt. The next operation starts its own attempt count.",
  ],
  [
    "nextRetryAt",
    "number | null",
    "null",
    "Unix timestamp in milliseconds. Render a countdown from this value while status is retrying.",
  ],
  [
    "error",
    "UploadError | undefined",
    "Unset",
    "code, message and optional HTTP status for validation or transfer failures.",
  ],
  [
    "removing",
    "boolean",
    "false",
    "True while your onRemove callback is pending.",
  ],
  [
    "removeError",
    "UploadError | undefined",
    "Unset",
    "Application deletion failed. The completed file remains in the list.",
  ],
];
export const methods: Row[] = [
  [
    "getSnapshot()",
    "UploaderSnapshot",
    "Read",
    "items, cleanups, disabled, readOnly, restored and optional persistenceError.",
  ],
  [
    "getItem(id)",
    "UploadItem | undefined",
    "Read",
    "Read one row without subscribing to the entire list.",
  ],
  [
    "subscribe(listener)",
    "() => void",
    "Read",
    "Listen for snapshot updates. Call the returned function to unsubscribe.",
  ],
  [
    "subscribeItem(id, listener)",
    "() => void",
    "Read",
    "Listen only to one row. A transfer in another row does not notify this listener.",
  ],
  [
    "add(files)",
    "Promise<string[]>",
    "Selection",
    "Validate Files from an input, drop event or application code. Returns their local IDs, including rejected rows with visible errors.",
  ],
  [
    "restore()",
    "Promise<void>",
    "Persistence",
    "Load persisted records once. UI Roots call it after mount. Unfinished records become awaiting-file.",
  ],
  [
    "attach(id, file)",
    "Promise<void>",
    "Resume",
    "Associate the original file with an inactive row and abort its previous validator. Canceled rows keep their state so Retry creates a new session. Completed rows reject attach. Reset expired rows first. Resume verifies every confirmed chunk.",
  ],
  [
    "start(id?)",
    "void",
    "Transfer",
    "Queue one row or all eligible rows. Canceled rows start with a new session. Failed validation is not bypassed.",
  ],
  [
    "pause(id)",
    "void",
    "Transfer",
    "Abort current requests and retry timers while keeping the session.",
  ],
  [
    "resume(id)",
    "void",
    "Transfer",
    "Queue a paused transfer. A chunked transport first probes the server.",
  ],
  [
    "retry(id)",
    "void",
    "Transfer",
    "Queue a failed or canceled transfer. Canceled transfers use a new session and send from the beginning. Other chunked retries reconcile saved parts.",
  ],
  [
    "cancel(id)",
    "Promise<void>",
    "Cleanup",
    "Stop an unfinished transfer and request temporary-data cleanup. Observe snapshot.cleanups for a remote cleanup failure.",
  ],
  [
    "reset(id)",
    "Promise<void>",
    "Transfer",
    "Discard the checkpoint, create a new request key and retain the selected File. The previous session has its own cleanup record. Completed records cannot reset.",
  ],
  [
    "remove(id)",
    "Promise<void>",
    "Catalog",
    "Call onRemove for a completed file. A failure sets removeError and leaves the row in place.",
  ],
  [
    "forget(id)",
    "void",
    "Local list",
    "Remove the local row without deleting the remote file.",
  ],
  [
    "retryCleanup(id)",
    "Promise<void>",
    "Cleanup",
    "Retry a failed cleanup record by its cleanup ID, not its item ID.",
  ],
  [
    "addExisting(items)",
    "void",
    "Catalog",
    "Append completed server records. Duplicate IDs are ignored. No File object is needed.",
  ],
  [
    "loadHistory(cursor?)",
    "Promise<string | undefined>",
    "Catalog",
    "Run the configured loader and return its next cursor. Your UI owns loading indicators and pagination buttons.",
  ],
  [
    "setOptions({ disabled?, readOnly? })",
    "void",
    "Interaction",
    "Change interaction flags without replacing the store or stopping active transfers.",
  ],
  [
    "destroy()",
    "void",
    "Lifecycle",
    "Abort requests, clear timers and remove subscriptions. An externally supplied store belongs to the application.",
  ],
];
export const states: Row[] = [
  ["idle", "Ready", "start", "Accepted file waiting for a start action."],
  [
    "validating",
    "Checking selection",
    "cancel",
    "Async file validation is running.",
  ],
  [
    "queued",
    "Waiting for a slot",
    "pause or cancel",
    "Concurrency limits are holding this file.",
  ],
  [
    "awaiting-file",
    "Original file required",
    "attach then resume",
    "Restored metadata has no local File.",
  ],
  [
    "verifying",
    "Checking saved data",
    "pause or cancel",
    "Server checkpoint or local chunk identities are being verified.",
  ],
  [
    "uploading",
    "Sending",
    "pause or cancel",
    "Creation or data requests are active.",
  ],
  [
    "retrying",
    "Waiting to retry",
    "pause or cancel",
    "nextRetryAt provides the countdown deadline.",
  ],
  [
    "paused",
    "Stopped locally",
    "resume or reset",
    "Session remains available.",
  ],
  [
    "finalizing",
    "Server is finishing",
    "pause or cancel",
    "All bytes may already be saved. Wait for confirmed completion.",
  ],
  [
    "completed",
    "Saved",
    "remove or forget",
    "result is the confirmed response from your server.",
  ],
  [
    "failed",
    "Request or validation failed",
    "retry or reset",
    "Validation errors need a different file rather than another request.",
  ],
  [
    "canceled",
    "Canceled locally",
    "retry, reset or forget",
    "Remote cleanup may still be pending or failed in snapshot.cleanups.",
  ],
  [
    "expired",
    "Session expired",
    "reset",
    "The previous server checkpoint is no longer reusable.",
  ],
];
export const parts: Row[] = [
  [
    "Root",
    "options or store, restore",
    "Context only",
    "Creates one store from options or borrows an existing store. React and Svelte render children without a wrapper. Vue renders a fragment.",
  ],
  [
    "Input",
    "Native file input props",
    "input",
    "multiple, accept, disabled, class and selection events belong to your markup. Root flags also block selection.",
  ],
  [
    "Trigger",
    "Native button props and children",
    "button",
    "Opens an enabled Input in this Root. Supply your own label or icon.",
  ],
  [
    "Dropzone",
    "Native container props and children",
    "div",
    "Connects drag/drop and exposes data-dragging. Your content defines the empty and dragging views.",
  ],
  [
    "List",
    "as, children or slot receiving IDs",
    "ul",
    'Renders a stable ID collection. Use as="div" for a grid or as="tbody" for a table. Progress does not rebuild the ID list.',
  ],
  [
    "Item",
    "id, as, native props",
    "li",
    "Provides one item context. Key each row by its ID. Use as to match the parent markup. data-state follows the item status.",
  ],
  [
    "Preview",
    "Renderer receiving item and url",
    "No fixed markup",
    "Use an img, video or your own format icon. Local object URLs are revoked when the File changes or the component unmounts.",
  ],
  [
    "Name",
    "Children or slot, native props",
    "span",
    "Defaults to metadata.name. Custom content can replace it.",
  ],
  [
    "Metadata",
    "format(item), children or slot",
    "span",
    "Choose MIME, extension, size or your own metadata. The primitive does not impose a particular sentence.",
  ],
  [
    "Progress",
    "Children or slot receiving item",
    "div",
    "Adds progressbar semantics. Render the bar, percentage, bytes or ETA yourself. Null progress omits aria-valuenow.",
  ],
  [
    "Status",
    "labels keyed by UploadStatus",
    "span",
    "Replace individual status labels or render your own content.",
  ],
  [
    "Output",
    "Renderer receiving snapshot",
    "No fixed markup",
    "Read selected or completed records anywhere inside the Root. Astro and Vanilla use data-upload-output with a custom renderOutput callback when needed.",
  ],
  [
    "Action",
    "action, itemId, native button props",
    "button",
    "start, pause, resume, retry, cancel, reset, remove or forget. In an Item, its ID is inherited. Outside an Item supply itemId, except start can target the entire queue.",
  ],
];
